paths:
  base_paths:
  - E:\Cavity_Flow_Results\90degree_250light_250hz_1000dt_0
  source_paths:
  - F:\181124_polyamide\90degree_250light_250hz_1000dt_0
  active_paths:
  - 0
  camera_numbers:
  - 1
  camera_count: 1
  camera_subfolders: []
images:
  image_format:
  - Camera%d.cine
  vector_format:
  - '%05d.mat'
  dtype: float32
  image_type: cine
  use_camera_subfolders: false
  start_index: 1
  frame_stride: 1
  pair_stride: 2
  pairing_preset: skip_frames
  num_loops: 1
  num_images: 7200
  image_shape:
  - 1200
  - 2560
batches:
  size: 50
logging:
  file: pypiv.log
  level: INFO
  console: true
processing:
  backend: cpu
  debug: false
  auto_compute_params: false
  omp_threads: 4
  dask_workers_per_node: 4
  dask_memory_limit: 12GB
  dask_max_in_flight_per_worker: 2
  open_dashboard: false
  dask_nanny: false
  post_processing_workers: 16
  always_batch: true
  instantaneous: true
  ensemble: false
outlier_detection:
  enabled: true
  methods:
  - threshold: 0.25
    type: peak_mag
  - type: median_2d
    epsilon: 0.1
    threshold: 2
infilling:
  mid_pass:
    method: nearest
    parameters: {}
  final_pass:
    enabled: true
    method: biharmonic
    parameters: {}
ensemble_outlier_detection:
  enabled: true
  methods:
  - type: median_2d
    epsilon: 0.1
    threshold: 2
    size: 5
ensemble_infilling:
  mid_pass:
    method: biharmonic
    parameters: {}
  final_pass:
    enabled: true
    method: biharmonic
    parameters: {}
plots:
  save_extension: .png
  save_pickle: true
  fontsize: 14
  title_fontsize: 16
video:
  base_path_idx: 0
  camera: 1
  data_source: stereo
  variable: mag
  run: 3
  piv_type: instantaneous
  cmap: default
  lower: ''
  upper: ''
  fps: 30
  crf: 15
  resolution: 4k
  source_endpoint: regular
statistics:
  enabled_methods:
    inst_vorticity: true
    gamma2: false
    inst_divergence: false
    mean_velocity: false
    vorticity: false
    mean_vorticity: false
    tke: false
    inst_gamma: true
    mean_tke: false
    correlation_quality: true
    inst_stresses: false
    divergence: false
    inst_velocity: false
    gamma1: false
    mean_stresses: false
    mean_divergence: false
    fluctuating_velocity: false
  gamma_radius: 4
  save_figures: true
  type_name: instantaneous
  source_endpoint: regular
instantaneous_piv:
  window_size:
  - - 64
    - 64
  - - 32
    - 32
  - - 24
    - 24
  - - 16
    - 16
  overlap:
  - 50
  - 50
  - 50
  - 50
  runs:
  - 3
  - 4
  time_resolved: false
  window_type: gaussian
  num_peaks: 1
  peak_finder: gauss6
  secondary_peak: false
  predictor_smoothing: false
  save_mode: full
  save_compression: false
  image_warp_interpolation: lanczos
  dump_correlation_planes: false
ensemble_piv:
  fit_method: kspace
  kspace_shape: kx4
  kspace_floor: coloured
  skip_background_subtraction: false
  gradient_correction: true
  persist_images: false
  predictor_smoothing: false
  image_warp_interpolation: lanczos
  mask_center_pixel: true
  background_subtraction_method: correlation+dc_zero
  window_size:
  - - 64
    - 64
  - - 32
    - 32
  - - 8
    - 8
  overlap:
  - 50
  - 50
  - 50
  type:
  - std
  - std
  - single
  runs:
  - 1
  - 2
  - 3
  store_planes: true
  save_diagnostics: true
  sum_window:
  - 32
  - 32
  sum_fitting_window_enabled: true
  sum_fitting_window:
  - 16
  - 16
  resume_from_pass: 3
  window_type: square
  predictor_boundary_conditions: []
  per_pair_normalization: false
  predictor_rounding: false
  envelope_divide: false
calibration:
  calibration_sources:
  - E:\alk235\cam4_all_512_tiff\calibration
  active: charuco
filters:
- type: time
masking:
  enabled: true
  mask_file_pattern: mask_Cam%d.mat
  mask_threshold: 0.01
  mode: file
  rectangular:
    top: 0
    bottom: 0
    left: 0
    right: 0
merging:
  type_name: instantaneous
  base_path_idx: 0
  cameras: null
transforms:
  base_path_idx: 0
  type_name: instantaneous
  cameras:
    1:
      operations: []
  source_endpoint: regular
