paths:
  base_paths:
  - E:\alk235\cam4_all_512_tiff\Cam4\processed\time96_preproc
  source_paths:
  - E:\alk235\cam4_all_512_tiff\Cam4
  active_paths:
  - 0
  camera_numbers:
  - 1
  camera_count: 1
  camera_subfolders: []
images:
  image_format:
  - B%05d_A.tif
  - B%05d_B.tif
  vector_format:
  - '%05d.mat'
  dtype: float32
  image_type: standard
  use_camera_subfolders: false
  start_index: 1
  frame_stride: 0
  pair_stride: 1
  pairing_preset: ab_format
  num_loops: 1
  num_images: 2100
  image_shape:
  - 3536
  - 512
batches:
  size: 20
logging:
  file: pypiv.log
  level: INFO
  console: true
processing:
  backend: cpu
  debug: false
  auto_compute_params: false
  omp_threads: 3
  dask_workers_per_node: 5
  dask_memory_limit: 10GB
  dask_max_in_flight_per_worker: 2
  open_dashboard: true
  dask_nanny: false
  post_processing_workers: 16
  always_batch: true
  instantaneous: false
  ensemble: true
outlier_detection:
  enabled: true
  methods:
  - threshold: 0.25
    type: peak_mag
  - type: median_2d
    epsilon: 0.1
    threshold: 3
infilling:
  mid_pass:
    method: nearest
    parameters: {}
  final_pass:
    enabled: true
    method: biharmonic
    parameters: {}
ensemble_outlier_detection:
  enabled: true
  methods: []
ensemble_infilling:
  mid_pass:
    method: biharmonic
    parameters: {}
  final_pass:
    enabled: true
    method: biharmonic
    parameters: {}
plots:
  save_extension: .png
  save_pickle: true
  fontsize: 14
  title_fontsize: 16
video:
  base_path_idx: 0
  camera: 1
  data_source: stereo
  variable: mag
  run: 3
  piv_type: ensemble
  cmap: default
  lower: ''
  upper: ''
  fps: 30
  crf: 15
  resolution: 4k
  source_endpoint: regular
statistics:
  enabled_methods:
    inst_vorticity: false
    mean_divergence: false
    inst_gamma: false
    gamma2: false
    vorticity: false
    gamma1: false
    divergence: false
    inst_stresses: false
    mean_velocity: true
    inst_velocity: false
    fluctuating_velocity: false
    mean_stresses: true
    mean_tke: false
    inst_divergence: false
    tke: false
    mean_vorticity: false
    mean_peak_height: false
  gamma_radius: 4
  save_figures: true
  type_name: ensemble
  source_endpoint: regular
instantaneous_piv:
  window_size:
  - - 128
    - 128
  - - 64
    - 96
  - - 32
    - 96
  - - 16
    - 96
  - - 8
    - 96
  overlap:
  - 50
  - 50
  - 50
  - 50
  - 50
  runs:
  - 2
  - 3
  - 4
  - 5
  time_resolved: false
  window_type: gaussian
  num_peaks: 1
  peak_finder: gauss6
  secondary_peak: false
  predictor_smoothing: false
  save_mode: full
  save_compression: false
  image_warp_interpolation: lanczos
  dump_correlation_planes: true
ensemble_piv:
  fit_method: kspace
  skip_background_subtraction: false
  gradient_correction: true
  persist_images: false
  predictor_smoothing: false
  image_warp_interpolation: lanczos
  mask_center_pixel: true
  background_subtraction_method: window_mean
  window_size:
  - - 64
    - 96
  - - 32
    - 96
  - - 16
    - 96
  overlap:
  - 50
  - 50
  - 50
  type:
  - std
  - std
  - single
  runs:
  - 1
  - 2
  - 3
  store_planes: true
  save_diagnostics: true
  sum_window:
  - 48
  - 96
  sum_fitting_window_enabled: true
  sum_fitting_window:
  - 32
  - 32
  resume_from_pass: 0
  window_type: square
  predictor_boundary_conditions:
  - y_position: 0
    ux: 0
    uy: 0
    edge: bottom
  per_pair_normalization: true
  predictor_rounding: true
calibration:
  image_format: calib_Cam4_B00001_crop.tif
  num_images: 10
  image_type: standard
  zero_based_indexing: false
  use_camera_subfolders: false
  subfolder: enhanced
  camera_subfolders:
  - camera1
  - camera2
  - camera3
  - camera4
  - camera5
  path_order: camera_first
  active: dotboard
  piv_type: ensemble
  scale_factor:
    dt: 0.0057553
    px_per_mm: 13.653
    source_path_idx: 0
  dotboard:
    dot_spacing_mm: 10
    datum_frame: 1
    model_type: polynomial
    dt: 1
    fix_k2: true
  charuco:
    squares_h: 10
    squares_v: 7
    square_size: 0.03
    marker_ratio: 0.5
    aruco_dict: DICT_4X4_1000
    min_corners: 6
    source_path_idx: 0
    camera: 1
    model_type: pinhole
    dt: 1
  stereo_dotboard:
    dot_spacing_mm: 12.22
    datum_camera: 1
    datum_frame: 1
  stereo_charuco:
    datum_camera: 1
    datum_frame: 1
  calibration_sources:
  - E:\alk235\cam4_all_512_tiff\calibration
  global_coordinates:
    enabled: true
    datum_camera: 1
    datum_pixel: null
    datum_physical:
    - 0
    - 10
    datum_frame: 1
    overlap_points: []
    invert_ux: false
    overlap_pairs: []
  n_views: 1
  dt: 4.96e-05
  datum_frame: 1
  camera_pair:
  - 1
  - 2
  stepped:
    dot_spacing_mm: 15
    step_height_mm: 3
    board_thickness_mm: 14.8
  stepped_stereo:
    stereo_config: auto
    model_type: pinhole
    fix_k2: true
filters:
- type: meannorm
- type: time
masking:
  enabled: true
  mask_file_pattern: mask_Cam%d.mat
  mask_threshold: 0.01
  mode: file
  rectangular:
    top: 0
    bottom: 0
    left: 0
    right: 0
merging:
  type_name: ensemble
  base_path_idx: 0
  cameras: null
transforms:
  base_path_idx: 0
  type_name: ensemble
  cameras:
    1:
      operations: []
  source_endpoint: regular
