paths:
  base_paths:
  - C:\Users\mtt1e23\OneDrive - University of Southampton\Documents\#current_processing\query_JHTDB\Planar_Images_with_wall\bailey
  source_paths:
  - C:\Users\mtt1e23\Downloads\ims\ims
  camera_numbers:
  - 1
  - 2
  camera_count: 2
images:
  num_images: 100
  image_format:
  - loop=1.set
  vector_format:
  - '%05d.mat'
  time_resolved: false
  dtype: uint16
batches:
  size: 10
logging:
  file: pypiv.log
  level: INFO
  console: true
processing:
  instantaneous: true
  ensemble: false
  stereo: false
  backend: cpu
  debug: false
  auto_compute_params: true
  omp_threads: 2
  dask_workers_per_node: 20
  dask_threads_per_worker: 1
  dask_memory_limit: 2.5GB
  outlier_detection: false
post_processing:
- type: POD
  settings:
    k_modes: 1
    randomised: false
    stack_u_y: true
    normalise: false
    camera: 1
plots:
  save_extension: .png
  save_pickle: true
  fontsize: 14
  title_fontsize: 16
videos:
- endpoint: ''
  type: instantaneous
  use_merged: false
  variable: ux
  video_length: 100
- endpoint: ''
  type: gamma1
  use_merged: false
  variable: gamma1
  video_length: 100
statistics_extraction: null
instantaneous_piv:
  window_size:
  - - 128
    - 128
  - - 64
    - 64
  - - 32
    - 32
  overlap:
  - 50
  - 50
  - 50
  runs:
  - 3
  time_resolved: false
  window_type: gaussian
  num_peaks: 1
  peak_finder: gauss6
  secondary_peak: false
ensemble_piv:
  runs:
  - 5
  filters:
  - type: time
  batch_size: 50
calibration_format:
  image_format: calib%05d.tif
calibration:
  active: stereo
  scale_factor:
    dt: 0.01
    px_per_mm: 3.41
  pinhole:
    source_path_idx: 1
    camera: 1
    image_index: 0
    file_pattern: calib%05d.tif
    pattern_cols: 10
    pattern_rows: 10
    dot_spacing_mm: 28.89
    enhance_dots: true
    asymmetric: false
    dot_distance_mm: 28.9
    grid_tolerance: 0.5
    ransac_threshold: 3
    dt: 1
  stereo:
    source_path_idx: 0
    camera_pair:
    - 1
    - 2
    file_pattern: planar_calibration_plate_*.tif
    pattern_cols: 10
    pattern_rows: 10
    dot_spacing_mm: 28.89
    enhance_dots: true
    asymmetric: false
    dt: 2
  image_format: calib%05d.tiff
filters:
- type: time
  batch_size: 50
masking:
  enabled: true
  mask_file_pattern: mask_Cam%d.mat
  mask_threshold: 0.01
  mode: rectangular
  rectangular:
    top: 64
    bottom: 64
    left: 0
    right: 0
