paths:
  base_paths:
  - C:\Users\mtt1e23\OneDrive - University of Southampton\Documents\#current_processing\4000_images_channel\planar_timing_instantaneous
  source_paths:
  - C:\Users\mtt1e23\OneDrive - University of Southampton\Documents\#current_processing\4000_images_channel\planar_images
  active_paths:
  - 0
  camera_numbers:
  - 1
  camera_count: 1
  camera_subfolders: []
images:
  num_images: 4000
  image_format:
  - B%05d_A.tif
  - B%05d_B.tif
  vector_format:
  - '%05d.mat'
  dtype: float32
  image_type: standard
  use_camera_subfolders: false
  start_index: 1
  frame_stride: 0
  pair_stride: 1
  pairing_preset: ab_format
  per_loop_frame_pairs: 4000
  num_loops: 1
  num_frame_pairs: 4000
batches:
  size: 10
logging:
  file: pypiv.log
  level: INFO
  console: true
processing:
  backend: cpu
  debug: false
  auto_compute_params: false
  omp_threads: 2
  dask_workers_per_node: 15
  dask_memory_limit: 3.5GB
  dask_max_in_flight_per_worker: 2
  open_dashboard: false
  post_processing_workers: 16
  always_batch: true
  instantaneous: true
  ensemble: false
outlier_detection:
  enabled: true
  methods:
  - threshold: 0.25
    type: peak_mag
infilling:
  mid_pass:
    method: local_median
    parameters: {}
  final_pass:
    enabled: true
    method: local_median
    parameters: {}
ensemble_outlier_detection:
  enabled: false
  methods: []
ensemble_infilling:
  mid_pass:
    method: local_median
    parameters: {}
  final_pass:
    enabled: true
    method: local_median
    parameters: {}
plots:
  save_extension: .png
  save_pickle: true
  fontsize: 14
  title_fontsize: 16
instantaneous_piv:
  window_size:
  - - 128
    - 128
  - - 64
    - 64
  - - 32
    - 32
  - - 16
    - 16
  overlap:
  - 50
  - 50
  - 50
  - 50
  runs:
  - 4
  time_resolved: false
  window_type: gaussian
  num_peaks: 1
  peak_finder: gauss3
  secondary_peak: false
  predictor_smoothing: false
  save_mode: minimal
  save_compression: false
  image_warp_interpolation: cubic
calibration:
  active: scale_factor
  piv_type: instantaneous
  scale_factor:
    dt: 0.0057553
    px_per_mm: 13.653
    source_path_idx: 0
filters: []
masking:
  enabled: true
  mask_file_pattern: mask_Cam%d.mat
  mask_threshold: 0.01
  mode: file
  rectangular:
    top: 0
    bottom: 0
    left: 0
    right: 0
