paths:
  base_path: "/Users/morgan/Library/CloudStorage/OneDrive-UniversityofSouthampton/Documents/#current_processing/query_JHTDB/Planar_Images_with_wall/test_images"
  camera_folders:
    - "Cam1"
logging:
  file: "pypiv.log" 
  level: "INFO"     
  console: True

processing:
  backend: "cpu"
  debug: False
  omp_threads: 5
  dask_workers_per_node: 4
  dask_threads_per_worker: 1
  dask_memory_limit: "3GB"

images:
  num_images: 28
  image_format: "B%05d_A.tif"
  shape: [1024,1024]

piv:
  type: "instantaneous"
  chunk_size: 7
  window_type: "gaussian"
  window_size:
  - [128,128]
  - [64,64]
  - [32,32]
  - [16,16]
  - [16,16]
  - [16,16]
  overlap:
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
  num_peaks: 1
  dt: 1
  peak_finder: "gauss6"
  secondary_peak: False
  epsilon:
  epsilon_threshold: 

preprocessing:
  filters:
    # - type: "clip"
    #   threshold: [0, 255]
    #   n: 2.0
    # - type: "invert"
    #   offset: 255
    # - type: "transpose"
    # - type: "time"
