batches:
  batch_size: 10
ensemble_infilling:
  final_pass:
    method: local_median
    parameters:
      ksize: 3
  mid_pass:
    method: local_median
    parameters:
      ksize: 3
ensemble_outlier_detection:
  enabled: true
  methods:
  - epsilon: 0.1
    threshold: 3.0
    type: median_2d
ensemble_piv:
  fit_method: kspace
  gradient_correction: true
  overlap:
  - 50
  - 50
  - 50
  peak_finder: gaussian
  predictor_smoothing: false
  runs:
  - 2
  - 3
  sum_fitting_window:
  - 16
  - 16
  sum_fitting_window_enabled: true
  sum_window:
  - 32
  - 32
  type:
  - std
  - single
  - single
  window_size:
  - - 32
    - 32
  - - 16
    - 16
  - - 16
    - 16
filters: []
images:
  frame_stride: 0
  image_format:
  - B%05d_A.tif
  - B%05d_B.tif
  image_type: standard
  num_images: 20
  pair_stride: 1
  pairing_preset: ab_format
  start_index: 1
infilling:
  final_pass:
    method: local_median
    parameters:
      ksize: 3
  mid_pass:
    method: local_median
    parameters:
      ksize: 3
masking:
  enabled: false
outlier_detection:
  enabled: true
  methods:
  - epsilon: 0.1
    threshold: 3.0
    type: median_2d
paths:
  base_paths:
  - /Users/morgan/Documents/CODE/PIVTOOLS_FULL_STACK/PyPIVTools-fftw/unit-tests/poiseuille_ensemble/test_workspace_kspace/output
  camera_count: 1
  camera_numbers:
  - 1
  source_paths:
  - /Users/morgan/Documents/CODE/PIVTOOLS_FULL_STACK/PyPIVTools-fftw/unit-tests/poiseuille_ensemble/test_workspace_kspace/source
processing:
  backend: cpu
  dask_max_in_flight_per_worker: 3
  dask_memory_limit: 4GB
  dask_workers_per_node: 2
  omp_threads: 4
