#!/usr/bin/env python3
"""
test_polynomial_calibration_recovery.py

Integration tests for the detector → polynomial fit → config → calibrator pipeline.

Uses synthetic calibration images generated by generate_synthetic_calibration.py.
Tests both dotboard and ChArUco detector paths with model_type="polynomial".

Verifies:
  - Detectors succeed with model_type="polynomial"
  - Polynomial coefficients are saved to config.yaml
  - PolynomialVectorCalibrator can load from config and calibrate points
  - Config round-trip: known calibration points recover correct world positions

Usage:
    pytest unit-tests/test_polynomial_calibration_recovery.py -v
"""

import shutil
import sys
from pathlib import Path

import cv2
import numpy as np
import pytest
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pivtools_core.config import Config, reload_config
from pivtools_gui.calibration.calibration_poly.polynomial_calibration_production import (
    PolynomialVectorCalibrator,
)
from pivtools_cli.synthetic_calibration_common import make_camera_matrix, make_poses

# ---------------------------------------------------------------------------
# Paths to pre-generated synthetic data
# ---------------------------------------------------------------------------
UNIT_DIR = Path(__file__).resolve().parent
SYNTH_DIR = UNIT_DIR / "synthetic_calibration"
GT_PATH = SYNTH_DIR / "ground_truth.npz"
DOTBOARD_DIR = SYNTH_DIR / "dotboard"
CHARUCO_DIR = SYNTH_DIR / "charuco"

# Grid parameters (must match generator)
DOT_COLS = 15
DOT_ROWS = 12
DOT_SPACING_MM = 15.0

# ChArUco parameters (must match generator)
SQUARES_H = 10
SQUARES_V = 7
SQUARE_SIZE = 0.030  # metres
MARKER_RATIO = 0.5
ARUCO_DICT = "DICT_4X4_1000"


def _skip_if_no_synth_data():
    if not GT_PATH.exists():
        pytest.skip(
            f"Synthetic calibration data not found at {SYNTH_DIR}. "
            "Run: python pivtools_cli/generate_synthetic_dotboard.py"
        )


# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture(scope="module")
def ground_truth():
    _skip_if_no_synth_data()
    return dict(np.load(str(GT_PATH)))


@pytest.fixture(scope="module")
def dotboard_polynomial_result(ground_truth):
    """Run dotboard detector with model_type='polynomial'."""
    if not DOTBOARD_DIR.exists():
        pytest.skip("Dotboard images not found")

    from pivtools_gui.calibration.calibration_planar.planar_calibration_production import (
        MultiViewCalibrator,
    )

    persist_dir = UNIT_DIR / "test_output" / "polynomial_dotboard"
    # Clean previous run to avoid stale images / detection files
    if persist_dir.exists():
        shutil.rmtree(persist_dir)
    persist_dir.mkdir(parents=True, exist_ok=True)
    img_dir = persist_dir / "images"
    img_dir.mkdir(exist_ok=True)

    # Polynomial calibration uses a single datum image (the board on the
    # laser sheet). Unlike pinhole, we are NOT building a multi-view
    # camera model — just fitting pixel↔world mapping for one plane.
    first_image = sorted(DOTBOARD_DIR.glob("calib*.png"))[0]
    shutil.copy2(first_image, img_dir / first_image.name)

    # Create a config so the detector can save polynomial params.
    # calibration_sources + image_format are required by
    # build_calibration_camera_path used in _get_camera_input_dir.
    config_path = persist_dir / "config.yaml"
    config_dict = {
        "paths": {"base_paths": [str(persist_dir)]},
        "calibration": {
            "dotboard": {"dt": 0.001},
            "calibration_sources": [str(img_dir)],
            "image_format": "calib%05d.png",
        },
    }
    with open(config_path, "w") as f:
        yaml.dump(config_dict, f)

    reload_config()
    cfg = Config(path=str(config_path))

    calibrator = MultiViewCalibrator(
        source_dir=str(img_dir),
        base_dir=str(persist_dir),
        camera_count=1,
        file_pattern="calib%05d.png",
        pattern_cols=DOT_COLS,
        pattern_rows=DOT_ROWS,
        dot_spacing_mm=DOT_SPACING_MM,
        asymmetric=False,
        model_type="polynomial",
        config=cfg,
    )

    result = calibrator.process_single_camera(1, save_visualizations=True)
    assert result["success"], f"Dotboard polynomial calibration failed: {result.get('error')}"
    result["_persist_dir"] = persist_dir
    result["_config_path"] = config_path
    return result


@pytest.fixture(scope="module")
def charuco_polynomial_result(ground_truth):
    """Run ChArUco detector with model_type='polynomial'."""
    if not CHARUCO_DIR.exists():
        pytest.skip("ChArUco images not found")

    from pivtools_gui.calibration.calibration_charuco.charuco_calibration_production import (
        ChArUcoCalibrator,
    )

    persist_dir = UNIT_DIR / "test_output" / "polynomial_charuco"
    if persist_dir.exists():
        shutil.rmtree(persist_dir)
    persist_dir.mkdir(parents=True, exist_ok=True)
    img_dir = persist_dir / "images"
    img_dir.mkdir(exist_ok=True)

    # Polynomial calibration uses a single datum image (same as dotboard).
    first_image = sorted(CHARUCO_DIR.glob("calib*.png"))[0]
    shutil.copy2(first_image, img_dir / first_image.name)

    config_path = persist_dir / "config.yaml"
    config_dict = {
        "paths": {"base_paths": [str(persist_dir)]},
        "calibration": {
            "charuco": {"dt": 0.001},
            "calibration_sources": [str(img_dir)],
            "image_format": "calib%05d.png",
        },
    }
    with open(config_path, "w") as f:
        yaml.dump(config_dict, f)

    reload_config()
    cfg = Config(path=str(config_path))

    calibrator = ChArUcoCalibrator(
        source_dir=str(img_dir),
        base_dir=str(persist_dir),
        camera_count=1,
        file_pattern="calib%05d.png",
        squares_h=SQUARES_H,
        squares_v=SQUARES_V,
        square_size=SQUARE_SIZE,
        marker_ratio=MARKER_RATIO,
        aruco_dict=ARUCO_DICT,
        min_corners=6,
        model_type="polynomial",
        config=cfg,
    )

    result = calibrator.process_camera(1, save_visualizations=True)
    assert result["success"], f"ChArUco polynomial calibration failed: {result.get('error')}"
    result["_persist_dir"] = persist_dir
    result["_config_path"] = config_path
    return result


# ===========================================================================
# Tests: Dotboard polynomial detection
# ===========================================================================

class TestDotboardPolynomial:
    """Verify dotboard detector succeeds with model_type='polynomial'."""

    def test_detection_succeeds(self, dotboard_polynomial_result):
        assert dotboard_polynomial_result["success"]
        assert dotboard_polynomial_result["model_type"] == "polynomial"

    def test_rms_error_low(self, dotboard_polynomial_result):
        rms = dotboard_polynomial_result["rms_error"]
        assert rms < 1.0, f"RMS fit error {rms:.4f} px too high"

    def test_mm_per_pixel_reasonable(self, dotboard_polynomial_result, ground_truth):
        """mm_per_pixel should be within 10% of ground truth scale."""
        mpp = dotboard_polynomial_result["mm_per_pixel"]
        # Compute expected scale from focal length and dot spacing
        gt_fx = ground_truth["camera_matrix"][0, 0]
        expected_mpp = DOT_SPACING_MM / (DOT_SPACING_MM / (DOT_SPACING_MM * gt_fx / 1000.0))
        # Just check it's physically reasonable (0.01 to 10 mm/px)
        assert 0.01 < mpp < 10.0, f"mm_per_pixel={mpp} out of reasonable range"

    def test_config_polynomial_params_written(self, dotboard_polynomial_result):
        """Config should have polynomial params for camera 1."""
        config_path = dotboard_polynomial_result["_config_path"]
        cfg = Config(path=str(config_path))
        cam_params = cfg.get_polynomial_camera_params(1)

        assert cam_params, "No polynomial camera params found in config"
        assert "origin" in cam_params
        assert "normalisation" in cam_params
        assert "mm_per_pixel" in cam_params
        assert "coefficients_x" in cam_params
        assert "coefficients_y" in cam_params
        assert "image_height" in cam_params
        assert len(cam_params["coefficients_x"]) == 10
        assert len(cam_params["coefficients_y"]) == 10
        assert cfg.polynomial_calibration.get("dt") == 0.001
        assert cfg.data["calibration"]["active"] == "polynomial"

    def test_config_round_trip_calibrate_point(self, dotboard_polynomial_result, ground_truth):
        """Load calibrator from config, calibrate known grid points, verify accuracy.

        This closes the seam: detector → fit → save_to_config → Config reload →
        PolynomialVectorCalibrator → calibrate_coordinates.

        Uses the ground truth camera model to project known dotboard grid
        points to pixel coordinates, converts to uncalibrated convention,
        runs through the polynomial calibrator, and verifies the output
        matches the known world coordinates within 1mm.
        """
        config_path = dotboard_polynomial_result["_config_path"]
        persist_dir = dotboard_polynomial_result["_persist_dir"]
        cfg = Config(path=str(config_path))

        cal = PolynomialVectorCalibrator(
            base_dir=str(persist_dir), camera_num=1, config=cfg,
        )

        # Recompute the exact poses used to generate the dotboard images.
        # make_poses is deterministic (seed=42), so this matches the generator.
        K = ground_truth["camera_matrix"]
        fx = K[0, 0]
        img_w = int(K[0, 2] * 2)

        board_w = (DOT_COLS - 1) * DOT_SPACING_MM / 1000.0
        board_h = (DOT_ROWS - 1) * DOT_SPACING_MM / 1000.0
        board_centre = np.array([board_w / 2, board_h / 2, 0])

        poses = make_poses(
            10, board_centre, fx, img_w, board_w,
            fill_fraction_range=(0.80, 0.55),
        )
        rvec, tvec = poses[0]  # First view (frontal, used as datum)
        dist_coeffs = np.zeros(5)

        # Test grid points spread across the board (safely interior)
        test_points = [(3, 2), (7, 5), (11, 9), (5, 8), (10, 3)]
        errors = []

        for col, row in test_points:
            x_world_mm = col * DOT_SPACING_MM
            y_world_mm = row * DOT_SPACING_MM

            # Project to raw pixel coordinates using ground truth camera model
            obj_pt = np.array([[[col * DOT_SPACING_MM / 1000.0,
                                 row * DOT_SPACING_MM / 1000.0,
                                 0.0]]], dtype=np.float64)
            proj, _ = cv2.projectPoints(obj_pt, rvec, tvec, K, dist_coeffs)
            px, py = proj[0, 0]

            # Convert raw pixel → uncalibrated convention
            x_uncal = np.array([px + 1.0])
            y_uncal = np.array([cal.image_height - py])

            x_mm, y_mm = cal.calibrate_coordinates(x_uncal, y_uncal)

            # Polynomial output: x_mm = world_x, y_mm = -world_y
            # (Y negated: camera y-down → physical y-up)
            err_x = abs(x_mm[0] - x_world_mm)
            err_y = abs(y_mm[0] - (-y_world_mm))
            errors.append((col, row, err_x, err_y))

            assert err_x < 0.2, (
                f"Grid ({col},{row}): x_mm={x_mm[0]:.3f}, expected {x_world_mm:.1f} "
                f"(error {err_x:.3f}mm)"
            )
            assert err_y < 0.2, (
                f"Grid ({col},{row}): y_mm={y_mm[0]:.3f}, expected {-y_world_mm:.1f} "
                f"(error {err_y:.3f}mm)"
            )


# ===========================================================================
# Tests: ChArUco polynomial detection
# ===========================================================================

class TestCharucoPolynomial:
    """Verify ChArUco detector succeeds with model_type='polynomial'."""

    def test_detection_succeeds(self, charuco_polynomial_result):
        assert charuco_polynomial_result["success"]
        assert charuco_polynomial_result["model_type"] == "polynomial"

    def test_rms_error_low(self, charuco_polynomial_result):
        rms = charuco_polynomial_result["rms_error"]
        assert rms < 1.0, f"RMS fit error {rms:.4f} px too high"

    def test_mm_per_pixel_reasonable(self, charuco_polynomial_result):
        mpp = charuco_polynomial_result["mm_per_pixel"]
        assert 0.01 < mpp < 10.0, f"mm_per_pixel={mpp} out of reasonable range"

    def test_config_polynomial_params_written(self, charuco_polynomial_result):
        """Config should have polynomial params for camera 1."""
        config_path = charuco_polynomial_result["_config_path"]
        cfg = Config(path=str(config_path))
        cam_params = cfg.get_polynomial_camera_params(1)

        assert cam_params, "No polynomial camera params found in config"
        assert "origin" in cam_params
        assert "normalisation" in cam_params
        assert "mm_per_pixel" in cam_params
        assert "coefficients_x" in cam_params
        assert "coefficients_y" in cam_params
        assert "image_height" in cam_params
        assert len(cam_params["coefficients_x"]) == 10
        assert len(cam_params["coefficients_y"]) == 10
        assert cfg.polynomial_calibration.get("dt") == 0.001
        assert cfg.data["calibration"]["active"] == "polynomial"

    def test_config_round_trip_calibrate_point(self, charuco_polynomial_result, ground_truth):
        """Load calibrator from config, calibrate known ChArUco corners, verify accuracy.

        Same seam test as dotboard but with ChArUco board geometry.
        ChArUco internal corners are at (col * square_size, row * square_size)
        in meters; the detector multiplies by 1000 to get mm before fitting.
        """
        config_path = charuco_polynomial_result["_config_path"]
        persist_dir = charuco_polynomial_result["_persist_dir"]
        cfg = Config(path=str(config_path))

        cal = PolynomialVectorCalibrator(
            base_dir=str(persist_dir), camera_num=1, config=cfg,
        )

        # Recompute exact poses for the ChArUco board
        K = ground_truth["camera_matrix"]
        fx = K[0, 0]
        img_w = int(K[0, 2] * 2)

        board_w = SQUARES_H * SQUARE_SIZE  # 10 * 0.030 = 0.30m
        board_h = SQUARES_V * SQUARE_SIZE  # 7 * 0.030 = 0.21m
        board_centre = np.array([board_w / 2, board_h / 2, 0])

        poses = make_poses(
            10, board_centre, fx, img_w, board_w,
            fill_fraction_range=(0.85, 0.65),
        )
        rvec, tvec = poses[0]
        dist_coeffs = np.zeros(5)

        # ChArUco internal corners: col ∈ 1..SQUARES_H-1, row ∈ 1..SQUARES_V-1
        # World coords in meters: (col * SQUARE_SIZE, row * SQUARE_SIZE, 0)
        # World coords in mm (as fitted): (col * SQUARE_SIZE * 1000, row * SQUARE_SIZE * 1000)
        sq_mm = SQUARE_SIZE * 1000.0  # 30mm

        # Test points safely interior to the board
        test_points = [(2, 2), (5, 3), (8, 5), (4, 4)]

        for col, row in test_points:
            x_world_mm = col * sq_mm
            y_world_mm = row * sq_mm

            obj_pt = np.array([[[col * SQUARE_SIZE,
                                 row * SQUARE_SIZE,
                                 0.0]]], dtype=np.float64)
            proj, _ = cv2.projectPoints(obj_pt, rvec, tvec, K, dist_coeffs)
            px, py = proj[0, 0]

            x_uncal = np.array([px + 1.0])
            y_uncal = np.array([cal.image_height - py])

            x_mm, y_mm = cal.calibrate_coordinates(x_uncal, y_uncal)

            err_x = abs(x_mm[0] - x_world_mm)
            err_y = abs(y_mm[0] - (-y_world_mm))

            assert err_x < 0.2, (
                f"Corner ({col},{row}): x_mm={x_mm[0]:.3f}, expected {x_world_mm:.1f} "
                f"(error {err_x:.3f}mm)"
            )
            assert err_y < 0.2, (
                f"Corner ({col},{row}): y_mm={y_mm[0]:.3f}, expected {-y_world_mm:.1f} "
                f"(error {err_y:.3f}mm)"
            )


# ===========================================================================
# Tests: Cross-detector consistency
# ===========================================================================

class TestCrossDetectorConsistency:
    """Verify dotboard and ChArUco polynomial paths produce similar results."""

    def test_mm_per_pixel_agreement(self, dotboard_polynomial_result, charuco_polynomial_result):
        """Both detectors should estimate similar mm_per_pixel."""
        mpp_dot = dotboard_polynomial_result["mm_per_pixel"]
        mpp_cha = charuco_polynomial_result["mm_per_pixel"]

        # Polynomial uses single datum image — different board types with
        # different random perspectives produce moderate scale variation.
        # Allow 35% (wider than pinhole multi-view which constrains better).
        rel_diff = abs(mpp_dot - mpp_cha) / max(mpp_dot, mpp_cha)
        assert rel_diff < 0.35, (
            f"mm_per_pixel disagrees: dotboard={mpp_dot:.6f}, charuco={mpp_cha:.6f} "
            f"(rel_diff={rel_diff:.3f})"
        )

    def test_image_centre_calibration_agreement(
        self, dotboard_polynomial_result, charuco_polynomial_result, ground_truth
    ):
        """Both paths should give similar physical coordinates for image centre."""
        results = []
        for result in [dotboard_polynomial_result, charuco_polynomial_result]:
            config_path = result["_config_path"]
            persist_dir = result["_persist_dir"]
            cfg = Config(path=str(config_path))

            cal = PolynomialVectorCalibrator(
                base_dir=str(persist_dir), camera_num=1, config=cfg,
            )

            gt_cam = ground_truth["camera_matrix"]
            x_raw = gt_cam[0, 2]
            y_raw = gt_cam[1, 2]
            x_uncal = np.array([x_raw + 1.0])
            y_uncal = np.array([cal.image_height - y_raw])

            x_mm, y_mm = cal.calibrate_coordinates(x_uncal, y_uncal)
            results.append((x_mm[0], y_mm[0]))

        # Polynomial uses single datum image from different boards with
        # different random perspectives. Allow 60mm — the boards are
        # centred differently in the field of view.
        dx = abs(results[0][0] - results[1][0])
        dy = abs(results[0][1] - results[1][1])
        assert dx < 60.0, f"x_mm disagrees by {dx:.2f}mm at image centre"
        assert dy < 60.0, f"y_mm disagrees by {dy:.2f}mm at image centre"


# ===========================================================================
# Diagnostic figures (gated by --make-figures)
# ===========================================================================

class TestDiagnosticFigures:
    """Generate diagnostic plots when --make-figures is passed."""

    def test_make_figures(
        self, dotboard_polynomial_result, charuco_polynomial_result,
        ground_truth, make_figures,
    ):
        if not make_figures:
            pytest.skip("Pass --make-figures to generate diagnostic plots")

        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        out_dir = Path(__file__).resolve().parent / "test_output"
        out_dir.mkdir(exist_ok=True)

        K = ground_truth["camera_matrix"]
        fx = K[0, 0]
        img_w = int(K[0, 2] * 2)
        dist_coeffs = np.zeros(5)

        fig, axes = plt.subplots(1, 2, figsize=(16, 7))

        for ax, (label, result, grid_fn) in zip(axes, [
            ("Dotboard", dotboard_polynomial_result, self._dotboard_grid),
            ("ChArUco", charuco_polynomial_result, self._charuco_grid),
        ]):
            config_path = result["_config_path"]
            persist_dir = result["_persist_dir"]
            cfg = Config(path=str(config_path))
            cal = PolynomialVectorCalibrator(
                base_dir=str(persist_dir), camera_num=1, config=cfg,
            )

            board_centre, board_w, fill_range, world_pts_mm, rvec, tvec = grid_fn(
                K, fx, img_w,
            )

            xs, ys, errs = [], [], []
            for x_world_mm, y_world_mm, obj_pt_m in world_pts_mm:
                obj_3d = np.array([[[obj_pt_m[0], obj_pt_m[1], 0.0]]], dtype=np.float64)
                proj, _ = cv2.projectPoints(obj_3d, rvec, tvec, K, dist_coeffs)
                px, py = proj[0, 0]

                x_uncal = np.array([px + 1.0])
                y_uncal = np.array([cal.image_height - py])
                x_mm, y_mm = cal.calibrate_coordinates(x_uncal, y_uncal)

                err_x = abs(x_mm[0] - x_world_mm)
                err_y = abs(y_mm[0] - (-y_world_mm))
                err = np.sqrt(err_x**2 + err_y**2)

                xs.append(x_world_mm)
                ys.append(y_world_mm)
                errs.append(err)

            sc = ax.scatter(xs, ys, c=errs, cmap="hot", s=40, vmin=0,
                           vmax=max(0.5, max(errs)))
            plt.colorbar(sc, ax=ax, label="Round-trip error (mm)")
            ax.set_xlabel("Board x (mm)")
            ax.set_ylabel("Board y (mm)")
            ax.set_title(f"{label} — max err: {max(errs):.3f} mm")
            ax.set_aspect("equal")

        plt.suptitle("Polynomial Round-Trip Spatial Error", fontsize=14, fontweight="bold")
        plt.tight_layout()

        out_path = out_dir / "polynomial_roundtrip_spatial.png"
        plt.savefig(out_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        print(f"\n  Spatial error figure saved: {out_path}")

    @staticmethod
    def _dotboard_grid(K, fx, img_w):
        board_w = (DOT_COLS - 1) * DOT_SPACING_MM / 1000.0
        board_h = (DOT_ROWS - 1) * DOT_SPACING_MM / 1000.0
        board_centre = np.array([board_w / 2, board_h / 2, 0])
        poses = make_poses(
            10, board_centre, fx, img_w, board_w,
            fill_fraction_range=(0.80, 0.55),
        )
        rvec, tvec = poses[0]

        pts = []
        for col in range(DOT_COLS):
            for row in range(DOT_ROWS):
                x_mm = col * DOT_SPACING_MM
                y_mm = row * DOT_SPACING_MM
                pts.append((x_mm, y_mm, (col * DOT_SPACING_MM / 1000.0,
                                          row * DOT_SPACING_MM / 1000.0)))
        return board_centre, board_w, (0.80, 0.55), pts, rvec, tvec

    @staticmethod
    def _charuco_grid(K, fx, img_w):
        board_w = SQUARES_H * SQUARE_SIZE
        board_h = SQUARES_V * SQUARE_SIZE
        board_centre = np.array([board_w / 2, board_h / 2, 0])
        poses = make_poses(
            10, board_centre, fx, img_w, board_w,
            fill_fraction_range=(0.85, 0.65),
        )
        rvec, tvec = poses[0]
        sq_mm = SQUARE_SIZE * 1000.0

        pts = []
        for col in range(1, SQUARES_H):
            for row in range(1, SQUARES_V):
                x_mm = col * sq_mm
                y_mm = row * sq_mm
                pts.append((x_mm, y_mm, (col * SQUARE_SIZE, row * SQUARE_SIZE)))
        return board_centre, board_w, (0.85, 0.65), pts, rvec, tvec
