#!/usr/bin/env python3
"""
test_charuco_calibration_recovery.py

Verifies that ChArUcoCalibrator recovers known ground-truth camera parameters
from synthetic calibration images generated by generate_synthetic_calibration.py.

Tolerances:
  - fx, fy within 2% of ground truth
  - cx, cy within 3 pixels
  - dist_coeffs all < 0.01 (synthetic images have zero distortion)
  - RMS reprojection error < 0.5 px
  - Camera matrix structure: skew=0, [2,2]=1
"""

import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
import pytest

# Ensure production code is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pivtools_gui.calibration.calibration_charuco.charuco_calibration_production import (
    ChArUcoCalibrator,
)

# Path to pre-generated synthetic data
SYNTH_DIR = Path(__file__).resolve().parent / "synthetic_calibration"
GT_PATH = SYNTH_DIR / "ground_truth.npz"
CHARUCO_DIR = SYNTH_DIR / "charuco"

# Board parameters (must match generator)
SQUARES_H = 10
SQUARES_V = 7
SQUARE_SIZE = 0.030  # metres
MARKER_RATIO = 0.5
ARUCO_DICT = "DICT_4X4_1000"


@pytest.fixture(scope="module")
def ground_truth():
    """Load ground-truth camera parameters."""
    if not GT_PATH.exists():
        pytest.fail(
            f"Synthetic data not found at {SYNTH_DIR}. "
            "Run: python pivtools_cli/generate_synthetic_charuco.py"
        )
    return dict(np.load(str(GT_PATH)))


@pytest.fixture(scope="module")
def calibration_result(ground_truth):
    """Run ChArUco calibration once, share result across all tests."""
    if not CHARUCO_DIR.exists():
        pytest.fail("Charuco images not found. Run: python pivtools_cli/generate_synthetic_charuco.py")

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        img_dir = tmpdir / "images"
        img_dir.mkdir()

        # Copy synthetic images into temp dir
        for src in sorted(CHARUCO_DIR.glob("calib*.png")):
            shutil.copy2(src, img_dir / src.name)

        calibrator = ChArUcoCalibrator(
            source_dir=str(img_dir),
            base_dir=str(tmpdir),
            camera_count=1,
            file_pattern="calib%05d.png",
            squares_h=SQUARES_H,
            squares_v=SQUARES_V,
            square_size=SQUARE_SIZE,
            marker_ratio=MARKER_RATIO,
            aruco_dict=ARUCO_DICT,
            min_corners=6,
        )

        result = calibrator.process_camera(1, save_visualizations=False)

    assert result["success"], f"Calibration failed: {result.get('error')}"
    return result


# ------------------------------------------------------------------
# Tests
# ------------------------------------------------------------------

def test_calibration_succeeds(calibration_result):
    """Sanity check: calibration returned success."""
    assert calibration_result["success"]


def test_focal_length_recovery(calibration_result, ground_truth):
    """fx and fy within 2% of ground truth."""
    cam = np.array(calibration_result["camera_matrix"])
    gt = ground_truth["camera_matrix"]

    fx_err = abs(cam[0, 0] - gt[0, 0]) / gt[0, 0]
    fy_err = abs(cam[1, 1] - gt[1, 1]) / gt[1, 1]

    assert fx_err < 0.02, f"fx error {fx_err:.4f} exceeds 2% (got {cam[0,0]:.1f}, expected {gt[0,0]:.1f})"
    assert fy_err < 0.02, f"fy error {fy_err:.4f} exceeds 2% (got {cam[1,1]:.1f}, expected {gt[1,1]:.1f})"


def test_principal_point_recovery(calibration_result, ground_truth):
    """cx and cy within 3 pixels of ground truth."""
    cam = np.array(calibration_result["camera_matrix"])
    gt = ground_truth["camera_matrix"]

    cx_err = abs(cam[0, 2] - gt[0, 2])
    cy_err = abs(cam[1, 2] - gt[1, 2])

    assert cx_err < 3.0, f"cx error {cx_err:.2f} px (got {cam[0,2]:.1f}, expected {gt[0,2]:.1f})"
    assert cy_err < 3.0, f"cy error {cy_err:.2f} px (got {cam[1,2]:.1f}, expected {gt[1,2]:.1f})"


def test_distortion_near_zero(calibration_result):
    """Distortion coefficients near zero (synthetic data has none).

    cv2.calibrateCamera always fits small spurious distortion when the true
    distortion is zero.  Radial coefficients (k1, k2, k3) can be larger
    than tangential (p1, p2) due to the radial-tangential coupling.
    """
    dist = np.array(calibration_result["dist_coeffs"])
    # k1, k2 (radial)
    assert abs(dist[0]) < 0.05, f"dist_coeffs[0] (k1) = {dist[0]:.6f}"
    assert abs(dist[1]) < 0.05, f"dist_coeffs[1] (k2) = {dist[1]:.6f}"
    # p1, p2 (tangential)
    assert abs(dist[2]) < 0.02, f"dist_coeffs[2] (p1) = {dist[2]:.6f}"
    assert abs(dist[3]) < 0.02, f"dist_coeffs[3] (p2) = {dist[3]:.6f}"
    # k3 (higher-order radial)
    assert abs(dist[4]) < 0.10, f"dist_coeffs[4] (k3) = {dist[4]:.6f}"


def test_rms_reprojection_error(calibration_result):
    """RMS reprojection error < 0.5 pixels."""
    rms = calibration_result["rms_error"]
    assert rms < 0.5, f"RMS error {rms:.4f} px exceeds 0.5 px threshold"


def test_camera_matrix_structure(calibration_result):
    """Camera matrix has correct structure: skew=0, [2,2]=1."""
    cam = np.array(calibration_result["camera_matrix"])
    assert cam.shape == (3, 3)
    assert cam[2, 2] == 1.0, f"[2,2] = {cam[2,2]}"
    assert cam[0, 1] == 0.0, f"skew = {cam[0,1]}"
    assert cam[1, 0] == 0.0
    assert cam[2, 0] == 0.0
    assert cam[2, 1] == 0.0


def test_num_images_used(calibration_result):
    """At least 3 images used (OpenCV minimum)."""
    assert calibration_result["num_images_used"] >= 3
