batches:
  batch_size: 1
calibration:
  active: polynomial
  polynomial:
    dt: 0.001
    cameras:
      '1':
        origin:
          x: 500.0
          y: 500.0
        normalisation:
          nx: 1000.0
          ny: 1000.0
        mm_per_pixel: 0.06677805644243831
        coefficients_x:
        - 500.00000000000057
        - 0.8358902625965839
        - -1.0802470029602773e-13
        - -0.7539692004224077
        - -1.5302393332884201e-13
        - 1.7541523789077473e-14
        - 1.9588284306107406e-13
        - -1.2429197902938998e-13
        - 2.9156651249183633e-13
        - -0.7548583031537818
        coefficients_y:
        - 500.0000000000007
        - -6.325372962501155e-14
        - 3.446847334555882e-14
        - 8.522349492778865e-14
        - 0.8359233437870506
        - 6.826897173581199e-14
        - -0.7540374900814801
        - -5.4119469322655446e-14
        - -0.754874841453436
        - 1.2448375663609573e-13
        image_height: 1000.0
filters: []
images:
  frame_stride: 0
  image_format:
  - B%05d_A.tif
  - B%05d_B.tif
  image_type: standard
  num_images: 1
  pair_stride: 1
  pairing_preset: ab_format
  start_index: 1
  vector_format:
  - B%05d.mat
infilling:
  final_pass:
    method: local_median
    parameters:
      ksize: 3
  mid_pass:
    method: local_median
    parameters:
      ksize: 3
instantaneous_piv:
  overlap:
  - 50
  peak_finder: gauss6
  runs:
  - 1
  window_size:
  - - 64
    - 64
  - - 32
    - 32
masking:
  enabled: false
outlier_detection:
  enabled: true
  methods:
  - epsilon: 0.1
    threshold: 3.0
    type: median_2d
paths:
  base_paths:
  - C:\Users\mtt1e23\OneDrive - University of Southampton\Documents\pivtools_fullstack\python-PIVTOOLs\unit-tests\poiseuille_cam_model\test_workspace_polynomial\output
  camera_count: 1
  camera_numbers:
  - 1
  source_paths:
  - C:\Users\mtt1e23\OneDrive - University of Southampton\Documents\pivtools_fullstack\python-PIVTOOLs\unit-tests\poiseuille_cam_model\test_workspace_polynomial\source
processing:
  backend: cpu
  dask_max_in_flight_per_worker: 3
  dask_memory_limit: 2GB
  dask_workers_per_node: 1
  omp_threads: 1
